config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Alonetone::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
  constraints Greenfield::Constraints do
    mount Greenfield::Engine => "/"
  end

  constraints(->(req){ !Greenfield::Constraints.matches?(req) }) do
    resources :groups

    mount Thredded::Engine => '/discuss'
    get '/upload', :to => 'assets#new'
    post '/listens', :to => 'listens#create', as: 'register_listen'
    get '/new_album', :to => 'playlists#new'
    get '/favorites', :to => 'playlists#favorites'
    get '/login', :to => 'user_sessions#new', :as => 'login'
    get '/logout', :to => 'user_sessions#destroy', as: 'logout', via: [:get, :post]
    resources :user_sessions

    get '/notifications/subscribe' => 'notifications#subscribe'
    get '/notifications/unsubscribe' => 'notifications#unsubscribe'

    get '/follow/:login' => 'following#follow', as: :follow
    get '/unfollow/:login' => 'following#unfollow', as: :unfollow
    get '/:login/toggle-follow' => 'following#toggle_follow', as: :toggle_follow

    # admin stuff
    get 'secretz' => 'admin#secretz'
    get 'toggle_theme' => 'admin#toggle_theme'

    get '404', to: "pages#four_oh_four"
    get '500', to: "pages#error"
    get 'ok', to: "pages#ok"

    # one-off pages
    get 'rpmchallenge' => 'pages#rpm_challenge'
    get '24houralbum' =>  'pages#twentyfour'

    resources :features, :user_reports

    get 'blog' => 'updates#index', :as => "blog_home"

    resources 'updates', :as => 'blog'
    resources :updates, :password_resets
    resources :comments do
      member do
        put :unspam
        put :spam
      end
    end

    get  'about/' => 'pages#about'

    %w(about press stats ok index privacy).each do |action|
      get "about/#{action}", to: "pages##{action}"
    end

    get 'signup', to: 'users#new'
    get 'settings', to: 'users#edit'
    get '/activate/:perishable_token', to: 'users#activate'

    # shortcut to profile
    get ':login/bio' => 'users#bio', :as => 'profile'

    get '/latest.:format' => 'assets#latest'

    # latest mp3s uploaded site-wide
    get '/latest/:latest' => 'assets#latest', :as => 'latest'

    get'/:login/listenfeed.:format' => 'assets#listen_feed', :as => 'listen_feed'

    get 'radio' =>'assets#radio', :as => 'radio_home'
    get 'radio/:source' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio_source_home'
    get 'radio/:source/:per_page/:page' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio'

    # top 40
    get  '/top/:top' => 'assets#top', :as => 'top'

    get '/users/by/activity/:page' => 'users#index', :sort => 'active', :defaults => {:page => 1}, :as => 'users_default'
    get '/users/(by/:sort(/:page))' => 'users#index', :defaults => {:page => 1}, :as => 'sorted_users'

    get ':login/history' => 'listens#index', :as => 'listens'

    get 'comments' => 'comments#index', :as => 'all_comments'
    get 'playlists' => 'playlists#all', :as => 'all_playlists'
    get ':login/comments' => 'comments#index', :as => 'user_comments'
    get ':login/stats.:format' => 'users#stats', :as => 'user_stats'

    resources :forums do
      resources :topics do
        resources :posts do
          member do
            put :unspam
            put :spam
          end
        end
      end
      resources :posts
    end

    resources :posts do
      collection do
        get :search
      end
    end


    get 'toggle_favorite' => 'users#toggle_favorite'

    match 'search' => 'search#index', via: [:get, :post]
    match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

    namespace :admin do
      resources :layouts
      resources :users
    end


    root :to => 'assets#latest'

    resources :users
    get ':login' => 'users#show', :as => "user_home"
    get ':login.:format' => 'users#show', :as => "user_feeds"

    resources :users, :path => "/" do
      member do
        post :attach_pic
        get :sudo
      end
      resources 'source_files' #:path_prefix => ':login'
      resources 'tracks', controller: :assets do
        member do
          get :share
          get :stats
          put :spam
          put :unspam
        end
        collection do
          get  :latest
          post :search
          get  :mass_edit
        end
        resources :comments,  only: [:create, :destroy]
      end
      resources :favorites
      resources :posts
      resources :playlists do
        collection do
          get :latest
          post :sort
          get :sort
        end
        member do
          post :attach_pic
          post :downloads, to: 'playlists#create_greenfield_download'
          get  :remove_track
          post :set_playlist_title
          post :set_playlist_description
          post :sort_tracks
          post :add_track
        end
        resources :comments
      end
      get '/playlists/:id/:asset_id', :to => 'playlists#show', as: 'show_track_in_playlist'
    end
  end
end

app/models/update.rb
class Update < ActiveRecord::Base
  has_permalink :title
  scope :recent, -> { order('created_at DESC') }

  has_many :comments, as: :commentable, dependent: :destroy

  # The following methods help us keep dry w/ comments
  def name
    "blog: #{title}"
  end

  def full_permalink
    "https://#{Alonetone.url}/blog/#{permalink}"
  end
end

# == Schema Information
#
# Table name: updates
#
#  id           :integer          not null, primary key
#  content      :text(65535)
#  content_html :text(65535)
#  permalink    :string(255)
#  revision     :integer
#  title        :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/updates_controller.rb
# Yup, this is the blog controller
class UpdatesController < ApplicationController
  before_action :require_login, except: %i[index show]
  before_action :gather_sidebar_fun, except: %i[destroy update]

  # GET /updates
  # GET /updates.xml
  def index
    @updates = Update.recent.includes(comments: [commenter: :pic]).paginate(
      per_page: 5,
      page: params[:page]
    )

    respond_to do |format|
      format.html # index.html.erb
      format.xml
      format.rss { render 'index.xml.builder' }
    end
  end

  # GET /updates/1
  # GET /updates/1.xml
  def show
    @update = Update.where(permalink: params[:id]).includes(comments: [commenter: :pic]).take!
    @previous = Update.where('created_at < ?', @update.created_at).order('created_at DESC').first
    @next = Update.where('created_at > ?', @update.created_at).order('created_at ASC').first
    @page_title = @update.title
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @update }
    end
  end

  def new
    @update = Update.new
  end

  def edit
    @update = Update.find_by_permalink(params[:id])
  end

  def create
    @update = Update.new(params[:update])
    if @update.save
      flash[:notice] = 'Update was successfully created.'
      redirect_to blog_path(@update.permalink)
    else
      format.html { render action: "new" }
    end
  end

  def update
    @update = Update.find_by_permalink(params[:id])
    if @update.update_attributes(params.permit(:title, :content))
      flash[:notice] = 'Blog entry updated.'
      redirect_to blog_path
    else
      render action: "edit"
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.xml
  def destroy
    @update = Update.find_by_permalink(params[:id])
    @update.destroy

    respond_to do |format|
      format.html { redirect_to(updates_url) }
      format.xml  { head :ok }
    end
  end

  protected

  def gather_sidebar_fun
    @recent_updates = Update.limit(10).order('created_at DESC')
  end

  def authorized?
    admin?
  end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_comment.html.erb
<div class="comment">
  <div class="comment_user">
    <% if comment.commenter %>
        <%= user_image_link(comment.commenter, :small)%>
    <% else %>
        <%= image_tag User.dummy_pic(:small)%>
    <% end %>
  </div>

  <div class="comment-body">
    <h2 class="h2-comment">  	
        <%= comment.commenter ? (link_to (h comment.commenter.name), user_home_path(comment.commenter)) : 'Guest' %>
        said <%= local_time_ago(comment.created_at) %></h2>
    <p class="p-comment"><%= "#{comment.body_html}".html_safe %></p>
  </div><!-- div end comment-body -->
</div><!-- div end comment -->

app/views/updates/_form.html.erb
<div id="comment_<%= update.id %>" class="comment_asset">
  <div class="comment_form">
    <%= form_for update.comments.build, id: "comment_form_#{update.id}" do |f| %>
     <div class="comment_as">
     <% if logged_in? %>
        <%= image_tag current_user.pic.pic(:small) %>Say something, <%= current_user.name %>:
     <% else %>
        <%= image_tag 'default/no-pic_white.svg' %> Say something as a guest or <%= link_to 'login', login_path %>:
     <% end %>
     </div>
     <%= f.text_area :body, rows:  4, cols:  60, class: 'double_trouble', id: "comment_body_#{update.id}"  %>
     <%= f.hidden_field :commentable_type, value:  'update', id: "comment_commentable_type_#{update.id}"%>
     <%= f.hidden_field :commentable_id, value:  update.id, id: "comment_commentable_id_#{update.id}"%>

     <div class="submit_wrapper">
        <div class="comment_waiting" >
          <div class="text"><!-- placeholder response text --></div>
        </div>
        <div class="small_spinner" style="display:none;"></div>
        <%= f.submit "make your comment", class: 'comment_submit',id: "submit_#{update.id}"%>
      </div>
    <% end %>
  </div>
</div>

app/views/updates/_sidebar.html.erb
<div class="sidebar">
    <div class="box">
        <h2 class="box static">Recent Grunts</h2>
        <div class="static_content">
            <ul>
            <% for update in @recent_updates %>
                <li><%= link_to update.title, blog_path(update.permalink) %></li>
            <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/updates/_update.html.erb
  <div class="post update">
     <% unless @updates %>
       <div class="post-title">
         <div class="post-title-left">
         <%= link_to '&laquo;Previous entry'.html_safe, blog_path(@previous.permalink), class:  'prev-next' if @previous %> 
         </div><!-- div end post-title-left -->
         <div class="post-title-mid">
         </div><!-- div end post-title-mid -->         
         <div class="post-title-right"><%= link_to 'Next entry&raquo;'.html_safe, blog_path(@next.permalink),class:  'prev-next' if @next%></div><!-- div end post-title-right -->        
       </div><!-- div end post-title -->
      <% end %>

   <div class="post-body">
     <h1 class="h1post"><%= link_to update.title, blog_path(update.permalink)%></h1>
     <h2 class="h2post">- posted by <a href ="/hero">hero</a> on <%= update.created_at.to_date.to_s(:long)%> - <%= update.comments.count %> comments -</h2>
      <%= markdown(update.content) %>
   </div><!-- div end post-body -->  
          
  <div id="comment_<%= update.id %>" class="comment_new" style="display:none;">
    <div class="comment_form">
      <%= form_for update.comments.new, id:"comment_form_#{update.id}" do |f| %>
       <div class="comment_as">
         <% if logged_in? %>
            <%= image_tag current_user.avatar(:tiny) %>Say something, <%= current_user.name %>:
         <% else %>
            <%= image_tag 'icons/user.png' %> Say something as a guest or <%= link_to 'login', login_path %>:
         <% end %>
       </div>
       <%= f.text_area :body, rows:  4, cols:  60, class: 'double_trouble', id:"comment_body_#{update.id}"  %>
       <%= f.hidden_field :commentable_type, value:  'Update', id: "comment_commentable_type_#{update.id}"%>
       <%= f.hidden_field :commentable_id, value:  update.id, id: "comment_commentable_id_#{update.id}"%>
 
       <div class="submit_wrapper">
          <div class="comment_waiting" >
            <div class="text"><!-- placeholder response text --></div>
          </div>
          <div class="small_spinner" style="display:none;"></div>
          <%= f.submit "make your comment", class:  'comment_submit',id:  "submit_#{update.id}"%> 
        </div>
      <% end %>  
    </div>
  </div>
   <div class="post-bot">
     <div class="post-bot-left <%= update.comments.count > 0 ? 'with_arrow' : '' %> "></div><!-- div end post-bot-left -->

     <div class="post-bot-mid"></div><!-- div end post-bot-mid -->         
     <div class="post-bot-right"><%= link_to "","#comment_#{update.id}", class:  'slide_open_href'%></div><!-- div end post-bot-right -->   
   </div><!-- div end post-body -->

   <div class="comment-all">
     <% update.comments.each do |comment| %>
        <%= render partial:  'updates/comment', locals:  {comment:  comment } if comment.body_html.present? %>
    <% end %>
   </div><!-- div end comment-all -->
 </div><!-- div end post -->

app/views/updates/edit.html.erb
<h1>Editing blog post</h1>

<%= error_messages_for :update %>

<%= form_for(@update, url: blog_path(@update.permalink)) do |f| %>
  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <b>Content</b><br />
    <%= f.text_area :content, rows: 50, cols: 100 %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', blog_path(@update.permalink) %> |
<%= link_to 'Back', blog_path %>

app/views/updates/index.html.erb
<%= render partial: @updates %>

<%= will_paginate @updates %>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= error_messages_for :update %>

<%= form_for @update do |f| %>
  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <b>Content</b><br />
    <%= f.text_area :content, rows: 25, cols: 70 %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', blog_home_path %>

app/views/updates/show.html.erb
<%= render @update %>