config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Alonetone::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
  constraints Greenfield::Constraints do
    mount Greenfield::Engine => "/"
  end

  constraints(->(req){ !Greenfield::Constraints.matches?(req) }) do
    resources :groups

    mount Thredded::Engine => '/discuss'
    get '/upload', :to => 'assets#new'
    post '/listens', :to => 'listens#create', as: 'register_listen'
    get '/new_album', :to => 'playlists#new'
    get '/favorites', :to => 'playlists#favorites'
    get '/login', :to => 'user_sessions#new', :as => 'login'
    get '/logout', :to => 'user_sessions#destroy', as: 'logout', via: [:get, :post]
    resources :user_sessions

    get '/notifications/subscribe' => 'notifications#subscribe'
    get '/notifications/unsubscribe' => 'notifications#unsubscribe'

    get '/follow/:login' => 'following#follow', as: :follow
    get '/unfollow/:login' => 'following#unfollow', as: :unfollow
    get '/:login/toggle-follow' => 'following#toggle_follow', as: :toggle_follow

    # admin stuff
    get 'secretz' => 'admin#secretz'
    get 'toggle_theme' => 'admin#toggle_theme'

    get '404', to: "pages#four_oh_four"
    get '500', to: "pages#error"
    get 'ok', to: "pages#ok"

    # one-off pages
    get 'rpmchallenge' => 'pages#rpm_challenge'
    get '24houralbum' =>  'pages#twentyfour'

    resources :features, :user_reports

    get 'blog' => 'updates#index', :as => "blog_home"

    resources 'updates', :as => 'blog'
    resources :updates, :password_resets
    resources :comments do
      member do
        put :unspam
        put :spam
      end
    end

    get  'about/' => 'pages#about'

    %w(about press stats ok index privacy).each do |action|
      get "about/#{action}", to: "pages##{action}"
    end

    get 'signup', to: 'users#new'
    get 'settings', to: 'users#edit'
    get '/activate/:perishable_token', to: 'users#activate'

    # shortcut to profile
    get ':login/bio' => 'users#bio', :as => 'profile'

    get '/latest.:format' => 'assets#latest'

    # latest mp3s uploaded site-wide
    get '/latest/:latest' => 'assets#latest', :as => 'latest'

    get'/:login/listenfeed.:format' => 'assets#listen_feed', :as => 'listen_feed'

    get 'radio' =>'assets#radio', :as => 'radio_home'
    get 'radio/:source' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio_source_home'
    get 'radio/:source/:per_page/:page' => 'assets#radio', :defaults => {:per_page => 5, :page => 1}, :as => 'radio'

    # top 40
    get  '/top/:top' => 'assets#top', :as => 'top'

    get '/users/by/activity/:page' => 'users#index', :sort => 'active', :defaults => {:page => 1}, :as => 'users_default'
    get '/users/(by/:sort(/:page))' => 'users#index', :defaults => {:page => 1}, :as => 'sorted_users'

    get ':login/history' => 'listens#index', :as => 'listens'

    get 'comments' => 'comments#index', :as => 'all_comments'
    get 'playlists' => 'playlists#all', :as => 'all_playlists'
    get ':login/comments' => 'comments#index', :as => 'user_comments'
    get ':login/stats.:format' => 'users#stats', :as => 'user_stats'

    resources :forums do
      resources :topics do
        resources :posts do
          member do
            put :unspam
            put :spam
          end
        end
      end
      resources :posts
    end

    resources :posts do
      collection do
        get :search
      end
    end


    get 'toggle_favorite' => 'users#toggle_favorite'

    match 'search' => 'search#index', via: [:get, :post]
    match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

    namespace :admin do
      resources :layouts
      resources :users
    end


    root :to => 'assets#latest'

    resources :users
    get ':login' => 'users#show', :as => "user_home"
    get ':login.:format' => 'users#show', :as => "user_feeds"

    resources :users, :path => "/" do
      member do
        post :attach_pic
        get :sudo
      end
      resources 'source_files' #:path_prefix => ':login'
      resources 'tracks', controller: :assets do
        member do
          get :share
          get :stats
          put :spam
          put :unspam
        end
        collection do
          get  :latest
          post :search
          get  :mass_edit
        end
        resources :comments,  only: [:create, :destroy]
      end
      resources :favorites
      resources :posts
      resources :playlists do
        collection do
          get :latest
          post :sort
          get :sort
        end
        member do
          post :attach_pic
          post :downloads, to: 'playlists#create_greenfield_download'
          get  :remove_track
          post :set_playlist_title
          post :set_playlist_description
          post :sort_tracks
          post :add_track
        end
        resources :comments
      end
      get '/playlists/:id/:asset_id', :to => 'playlists#show', as: 'show_track_in_playlist'
    end
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  include GreenfieldPlaylistDownloads
  include Listens

  before_action :find_user, except: :all
  before_action :find_playlists, except: %i[index new create all sort]
  before_action :require_login, except: %i[index show all]
  before_action :find_tracks, only: %i[show edit all]

  def all
    @playlists = Playlist.recent.only_public.with_pic.paginate(page: params[:page], per_page: 30)
  end

  # all user's playlists
  def index
    @page_title = @description = "#{@user.name}'s albums and playlists: "
    set_all_playlists
  end

  def sort
    respond_to do |format|
      format.html { @playlists = @user.playlists.include_private }
      format.js do
        params["playlist"].each_with_index do |id, position|
          @user.playlists.find(id).update_column(:position, position + 1)
        end
        head :ok
      end
    end
  end

  def favorites
    @playlist = @user.favorites
    redirect_to user_playlist_path(@user, @playlist)
  end

  def show
    @asset = find_asset_in_playlist
    respond_to do |format|
      format.html do
        lazily_create_waveform_if_needed if @asset
        @page_title = @description = "\"#{@playlist.title}\" by #{@user.name}"
        if request.xhr?
          render '/shared/_asset_white', layout: false
        else
          render 'show_white' if white_theme_enabled?
        end
      end
      format.mp3 do
        listen(@asset, register: false)
      end
      format.xml
    end
  end

  def new
    @playlist = @user.playlists.build(private: true)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @playlist }
    end
  end

  def edit
    set_assets
    @listens = @user.listened_to_tracks.preload(:user)
                    .select('distinct assets.*, listens.created_at').paginate(page: params[:listens_page], per_page: 10)
    @favorites = @user.favorites.tracks.paginate(page: params[:favorites_page], per_page: 10) if @user.favorites.present?
    if request.xhr?
      render_desired_partial
    elsif white_theme_enabled?
      render 'edit_white'
    end
  end

  def add_track
    id = params[:asset_id].split("_")[1]
    asset = Asset.find(id)
    @track = @playlist.tracks.create(asset: asset, user: @user)
    respond_to do |format|
      format.js do
        render plain: @track.id if white_theme_enabled?
      end
    end
  end

  def attach_pic
    if params[:pic].present?
      @pic = @playlist.build_pic(params[:pic].permit(:pic))
      flash[:notice] = 'Picture updated!' if @pic.save && @playlist.touch
    end
    flash[:error] = 'Error, picture not updated! Try again.' unless flash[:notice].present?
    redirect_to edit_user_playlist_path(@user, @playlist)
  end

  def remove_track
    @track = @playlist.tracks.find(params[:track_id])
    if @track&.destroy
      respond_to do |format|
        format.js { head(:ok) }
      end
    else
      head :ok
    end
  rescue ActiveRecord::RecordNotFound
    head(:bad_request)
  end

  def sort_tracks
    # get the params for this playlist
    params["track"].each_with_index do |id, position|
      @playlist.tracks.find(id).update_column(:position, position + 1)
    end
    head :ok
  rescue ActiveRecord::RecordNotFound, NoMethodError
    return head(:bad_request)
  end

  def create
    @playlist = @user.playlists.build(playlist_params)
    if @playlist.save
      flash[:notice] = 'Great, go ahead and add some tracks'
      redirect_to edit_user_playlist_path(@user, @playlist)
    else
       render action: "new"
    end
  end

  def update
    if @playlist.update_attributes(playlist_params)
      redirect_to edit_user_playlist_path(@user, @playlist), notice: 'Playlist was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @playlist.destroy
    flash[:notice] = "That playlist is gone."
    redirect_to(user_playlists_url(@user))
  end

  protected

  def find_asset_in_playlist
    Asset.where(id: @playlist.tracks.pluck(:asset_id), permalink: params[:asset_id]).take! if params[:asset_id].present?
  end

  def playlist_params
    params.require(:playlist).permit!
  end

  def render_desired_partial
    render partial: 'your_stuff.html.erb'     if params[:uploads_page]
    render partial: 'your_listens.html.erb'   if params[:listens_page]
    render partial: 'your_favorites.html.erb' if params[:favorites_page]
  end

  def set_assets
    @assets = @user.assets.recent.paginate(page: params[:uploads_page], per_page: 10)
  end

  def set_all_playlists
    @all_playlists =  current_user_is_admin_or_owner?(@user) ?
                      @user.playlists.include_private :
                      @user.playlists.only_public

    set_right_and_left_playlists if @all_playlists.present?
  end

  def set_right_and_left_playlists
    middle = (@all_playlists.size + 1) / 2
    @playlists_left  = @all_playlists[0...middle]
    @playlists_right = @all_playlists[middle..-1]
  end

  def authorized?
    @playlist.nil? || current_user_is_admin_or_owner?(@user) ||
      %w[ destroy admin edit update remove_track attach_pic sort_tracks
          add_track set_playlist_description set_playlist_title ].include?(action_name) == false
  end

  def find_playlists
    permalink = params[:permalink] || params[:id]
    @playlist = @user.playlists.where(permalink: permalink).first || @user.playlists.where(id: permalink).take!
  end

  def find_tracks
    @tracks = @playlist.tracks if @playlist
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def title_and_year_for(playlist)
    title = playlist.title.to_s
    title += " (#{playlist.year})" if playlist.year.present?
    title
  end

  def allow_greenfield_playlist_downloads?(user)
    user.greenfield_enabled? && Alonetone.storage.s3?
  end

  def svg_cover
    "<div class='no_pic'></div>".html_safe
  end

  def playlist_cover(playlist, size)
    if Alonetone.try(:show_dummy_pics) || playlist.has_no_cover?
      return svg_cover
    # greenfield size did not exist before this id
    elsif (size == :greenfield) && ((playlist.pic.id > 69806) && (playlist.pic.id < 72848))
      size = :original
    elsif ((size == :greenfield) || (size == :original)) && (playlist.pic.id < 69807)
      size = :album
      @old_cover_alert = true
    end
    image_tag playlist.cover(size)
  end

  def greenfield_upload_form(user, playlist)
    # leave these hashrokets. breaking spec/request/assets_controller_spec.rb
    # Will look into it later
    data = {
      'expected-content-type' => Greenfield::PlaylistDownload::CONTENT_TYPE.join(' '),
      'max-file-size' => Greenfield::PlaylistDownload::MAX_SIZE,
      'max-file-size-human' =>
        number_to_human_size(Greenfield::PlaylistDownload::MAX_SIZE).downcase
    }
    options = {
      id: "s3-uploader",
      key_starts_with: "greenfield/",
      acl: "authenticated-read",
      callback_url: downloads_user_playlist_path(user, playlist),
      max_file_size: Greenfield::PlaylistDownload::MAX_SIZE,
      data: data
    }
    s3_uploader_form(options) { yield("") }
  end

  def external_link_for(link)
    text = case link
           when /spotify/i
            service = 'spotify'
            '<i class="spotify"></i><span class="service-name">Spotify</span><span class="action-text">Stream</span>'
           when /app\=music/i
            service = 'apple'
            '<i class="apple_music"></i><span class="service-name">Apple Music</span><span class="action-text">Stream</span>'
           when /app\=itunes/i
            service = 'itunes'
            '<i class="itunes"></i><span class="service-name">iTunes</span><span class="action-text">Buy</span>'
           when /play\.google/i
      '<i class="fa fa-google"></i>Google<span class="action-text">Stream</span>'
           else
      '<i class="fa fa-link"></i>Website<span class="action-text">Visit</span>'
    end.html_safe
    link_to(text, link, class: service).html_safe
  end
end

app/views/playlists/_asset.html.erb
<%= content_tag :div, id: ("asset_#{asset.id}"), class: 'asset unopenable ' do %>
  <%= render layout: 'assets/asset_layout', locals: {asset: asset} do %>
     <%= link_to asset.user.name, user_home_path(asset.user), class: 'artist' %>
  <% end %>
<% end %>

app/views/playlists/_form.html.erb
<p>
  <label>Title</label>
  <%= f.text_field :title %>
</p>

<p>
  <label>Year released (e.g. 2019)</label>
  <%= f.text_field :year, size: 4 %>
</p>
<p>
  <label>Description</label>
  <%= f.text_area :description, rows: 4 %>
</p>

<p>
  <label>Hidden from the public?</label><br>
  <%= f.check_box :private %><br>
  <span style="font-size: 12px">(Playlist will always be hidden until they have more than 2 tracks)</span>
</p>

app/views/playlists/_inline_help.html.erb
<%= notice_for('edit_playlist',"Editing '#{@playlist.title}'") do %>
    <ol>
        <li>Find the track you want to add</li>
        <li>Drag track to your playlist on the left</li>
        <li>Repeat!</li>
        <li>Order tracks in your playlist by dragging them up and down</li>
    </ol>
<% end %>

app/views/playlists/_links.html.erb
<ul class="downloads-links">
  <% @playlist.greenfield_downloads.each do |download| %>
    <li>
     <%= link_to downloads_user_playlist_path(@playlist.user, @playlist, download, download.attachment_file_name) do %>
       <i class="fa fa-download"></i><%= download.title %><span class='action-text'>Download</span>
     <% end %>
   </li>
  <% end %>
</ul>

<ul class="external-links">
  <% [:link1, :link2, :link3].collect do |link| %>
    <% if valid_link = @playlist.send(link) %>
      <li>
        <%= external_link_for(valid_link) %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/playlists/_playlist_white.html.erb
<div class="playlist-sidebar">

  <%= link_to playlist_cover(@playlist, :original), user_playlist_path(@playlist.user, @playlist), class: 'small-cover', style: ('display:none;' unless @asset) %>
  <h1 class="<%= 'cover' unless @asset %>">
    <%= @playlist.title %>
  </h1>
  <h2>
    <span class="by">by</span> <%= link_to @user.display_name, user_home_path(@user) %>

  </h2>

  <ul class="tracklist">
  <% @playlist.tracks.each do |track| %>
    <li data-controller="playlist-playback" data-action="popstate@window->playlist-playback#popTrack ajax:success->playlist-playback#loadTrack" data-playlist-playback-id="<%= track.asset.id %>" class="<%= ' active' if track.asset == @asset %>">

    <!-- Play button automagically plays AND changes to relevant track details  -->
    <%= link_to user_show_track_in_playlist_path(@user, @playlist, track.asset),
      class: 'play-button', data: { target: "playlist-playback.play", action: "click->playlist-playback#togglePlay" }  do %>
      <i class="icon_play"></i>
    <% end %>

    <!-- Track title just switches track details-->
    <%= link_to user_show_track_in_playlist_path(@user, @playlist, track.asset), 
      remote: true, class: 'position-name-time', data: { target: "playlist-playback.loadTrack" } do %>
      <span class="track-position">
        <%= "%02d" % track.position %>.
      </span>
      <span class="track-name">
        <%= track.name %>
      </span>
      <span class='time-text'><%= track.asset.length %></span>
    <% end %>
    </li>
  <% end %>
  </ul>

  <div class="sidebar-downloads <%= 'anchor-at-bottom' if @playlist.tracks.count < 11 %>"
    style="<%= 'display:none' unless @asset %>">
    <ul class="downloads-links">
      <% @playlist.greenfield_downloads.each do |download| %>
        <li>
         <%= link_to downloads_user_playlist_path(@playlist.user, @playlist, download, download.attachment_file_name) do %>
           <i class="fa fa-download"></i><%= download.title %><span class='action-text'>Download</span>
         <% end %>
       </li>
      <% end %>
    </ul>

    <ul class="external-links">
      <% [:link1, :link2, :link3].collect do |link| %>
        <% if valid_link = @playlist.send(link) %>
          <li>
            <%= external_link_for(valid_link) %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>

    <% if authorized? %>
  <div class="edit_playlist_container">
    <%= link_to edit_user_playlist_path(@playlist.user, @playlist), class: 'edit_playlist', :title => 'edit this playlist' do %>
      edit playlist
    <% end %>
  </div>
  <% end %>

</div>

app/views/playlists/_share.html.erb
<h2 class="box">Share this playlist</h2>
<div class="box">
  <div class="static_content panel no_border">
    <h3>Link to this playlist</h3>
    <%= text_field_tag "link_#{playlist.id.to_s}","#{user_playlist_url(playlist.user.login, playlist)}", size: 50%>
  </div>
  <div class="static_content panel">
    <h3>Embed a flash player</h3>
    <%= text_area_tag "flash_player_#{playlist.id.to_s}", "<embed src=\"#{FLASH_PLAYER}\" width=\"320\" height=\"140\" allowfullscreen=\"true\" allowscriptaccess=\"always\" flashvars=\"&file=#{user_playlist_url(playlist.user, playlist, format: :xml)}&height=140&width=320&frontcolor=0x3C3C3C&backcolor=0xf3f3f3&lightcolor=0xFF944B&screencolor=0xFF944B&displaywidth=120&showdigits=false&showdownload=true\" />", rows: 3, cols: 50 %>
    (customize how it looks by visiting <%= link_to 'the setup wizard', 'http://www.jeroenwijering.com/?page=wizard&example=2'%>)
  </div>
</div>

app/views/playlists/_tracks.html.erb
<% div_for @playlist do %>
	<%= render partial: 'asset', collection: @tracks %>
<% end %>

app/views/playlists/_your_favorites.html.erb
<div id="your_favorites" class="playlist_source">
  <div class="mini_paginator">
    <%= will_paginate @favorites, {param_name: :favorites_page, ignore_get_params: true}%>
  </div>
	<div class="scriptaculous">
	  <%= render partial: 'playlists/asset', collection: @favorites.collect(&:asset) %>
	</div>
</div>

app/views/playlists/_your_stuff.html.erb
<div id="your_uploads" class="playlist_source">
  <div class="mini_paginator">
    <%= will_paginate @assets, {param_name: :uploads_page, ignore_get_params: true}%>
  </div>

	<div class="scriptaculous">
	  <%= render partial: 'playlists/asset', collection: @assets %>
	</div>
</div>

app/views/playlists/add_track.js.erb
<%= render partial: 'track.html.erb', object: @track %>

app/views/playlists/create_greenfield_download.js.erb
<% if @greenfield_download.new_record? %>
  $("#upload_<%= @unique_id %>").addClass('error');
  <% @greenfield_download.errors.full_messages.each do |error| %>
    $("#upload_<%= @unique_id %> ul.messages").append(
      $('<li>').text("<%= j error.html_safe %>")
    );
  <% end %>
<% else %>
  $("#upload_<%= @unique_id %> ul.messages").append(
    $('<li>').text("<%= j @greenfield_download.attachment_file_name %> was saved.")
  );
<% end %>

app/views/playlists/edit_white.html.erb
<%= error_messages_for :playlist %>

<div id="edit_playlist_info" class="faq box">
  <h2>Playlist Settings for "<%= @playlist.title %>"</h2>

    <div class="edit_playlist_columns">
      <div class="edit_playlist_left_column">
          <label>ALBUM ARTWORK</label>
          <%= link_to '#needstotriggerclickforform', :title => "#{@playlist.title}", :class => "cover" do %>
            <%= playlist_cover(@playlist, :original) %>
          <% end %>
          <%= form_for :pic, url: attach_pic_user_playlist_path(@user, @playlist), html: {multipart: true, method: :post} do |f| %>
            <%= f.file_field :pic  %>
            <%= submit_tag "Upload new Pic" %>
          <% end %>
          <p>
            Upload a square photo, 2000px by 2000px for best results.
          </p>
      </div>
      <%= simple_form_for [@user, @playlist], html: { class: 'edit_playlist_right_column' } do |f| %>
        <div class="edit_playlist_right_column_title_and_year">
          <%= f.input :title %>
          <%= f.input :year, input_html: {maxlength: 4, size: 4} %>
        </div>
        <div class="edit_playlist_right_column_links">
          <%= f.input :link1, placeholder: 'link to spotify, itunes, google play, etc' %>
          <%= f.input :link2, placeholder: 'another link' %>
        </div>

        <div class="edit_playlist_right_column_credits">
          <%= f.input :credits %>
        </div>

        <% if moderator? %>
          <%= f.simple_fields_for :greenfield_downloads do |sf| %>
            <%= sf.input :title, label: sf.object.attachment_file_name + ':' %>
          <% end %>
        <% end %>
        
        <div class="edit_playlist_right_column_private_and_hidden">
          <%= f.input :private %> &nbsp; | (Playlists are hidden until they have more than 2 tracks)
        </div>
    </div>
    <div class="edit_playlist_bottom">
      <%= link_to 'Delete playlist', user_playlist_path(@user, @playlist.permalink), method: :delete, data: { confirm: 'Are you sure, it will be gone forrrrreevrrrrrrr!' } %>
      <%= f.button :submit, "save playlist" %>
    </div>
    <% end %>
</div>
<%#= render 'add_greenfield_downloads' if allow_greenfield_playlist_downloads?(@user) %>
<!-- 
<div class="edit_playlist_pro_upload faq box">
  <div class="pro_upload_left">
    <h1>Professional Upload System&trade;</h1>
    <p>
      You can upload a ZIP file containing the playlist contents, and we'll populate the playlist for you.
    </p>
  </div>
  <a class="upload_zip" href="">
    Upload ZIP file
  </a>
</div>
--> 
<div id="columns" class="edit_playlist_columns" data-controller="playlist-edit">
  <div id="left">
    <p class="left_instructions">
      You can reorder your playlist by dragging your tracks. Remove them from the playlist with the <span class="remove-inner-inline"><%= render file: svg_path('svg/icon_x.svg') %></span>
 icon.
    </p>
    <div class="box">
    
    <h2 class="box"><%= @playlist.title %></h2>
    <div class="sortable" data-target="playlist-edit.sortable">
      <% @playlist.tracks.each do |track| %>
      <div class="asset playlist_asset" data-controller="normal-playback playlist-update" data-normal-playback-openable="false" id="track_<%= track.id %>">
        <%= render partial: 'assets/asset_white', locals: { asset: track.asset } %>
        <a href="#" class='remove' data-target="playlist-update.remove" data-action="playlist-update#remove">
          <div class="remove-inner">
              <%= render file: svg_path('svg/icon_x.svg') %>
          </div>
        </a>
      </div>
      <% end %>
    </div>
    </div>
    <div class="playlist_feedback" data-target="playlist-edit.feedback">
    </div>
     <% if @playlist.tracks.size > 0 %>
      <div class="playlist_size">
      <%= "<span class='playlist_size' data-target='playlist-edit.size'>#{@playlist.tracks.size}</span> tracks by #{@playlist.is_mix? ? "various artists" : @playlist.tracks.first.asset.user.display_name}".html_safe %>
      </div>
    <% end %>    
     <div class="spinner" data-target="playlist-edit.spinner">spinning...</div>
  </div>

  <div id="right">
    <p class="right_instructions">
       Click the <span class="add-inner-inline"><%= render file: svg_path('svg/icon_+.svg') %></span> icon on a track below to add it to the playlist selection.
    </p>
    <div id="playlist_sources" class="box draggable_wrapper">
      <div class="draggable_tracks">
        <h2 class="box">Available tracks</h2>
        <div id="playlist_tabs">
          <ul id="playlist_source_options" class="tabs" data-target="playlist-edit.tabs">
            <li><%= link_to 'Your Uploads', '#your_uploads', class: 'playlist_option', id: 'open_your_stuff' if @user.has_tracks? %></li>
            <li><%= link_to "Your Listens", "#your_listens", class: 'playlist_option', id: 'open_your_listens' %></li>
            <li><%= link_to "Favs", '#your_favorites', class: 'playlist_option', id: 'open_your_favorites' %></li>
          </ul>
          <div id="your_uploads" class="playlist_source">
            <div class="mini_paginator">
              <%= will_paginate @assets, {param_name: :uploads_page, ignore_get_params: true}%>
            </div>
            <% @assets.each do |asset| %>
              <div class="asset playlist_asset" data-controller="normal-playback playlist-update" data-normal-playback-openable="false" id="asset_<%= asset.id %>">
                <%= render partial: 'assets/asset_white', locals: { asset:asset } %>
                <a href="#" class='add' data-target="playlist-update.add" data-action="playlist-update#add">
                  <div class="add-inner">
                    <%= render file: svg_path('svg/icon_+.svg') %>
                  </div>
                </a>
                <a href="#" class='remove' data-target="playlist-update.remove" data-action="playlist-update#remove" style="display:none">
                  <div class="remove-inner">
                      <%= render file: svg_path('svg/icon_x.svg') %>
                  </div>
                </a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'add_track_url', add_track_user_playlist_path(@user, @playlist.permalink), 
    data: { target:'playlist-edit.addUrl' }, class: 'hidden add_url' %>  
  <%= link_to 'remove_track_url', remove_track_user_playlist_path(@user, @playlist.permalink), 
    data: { target:'playlist-edit.removeUrl' }, class: 'hidden remove_url' %>
  <%= link_to "sort tracks url", sort_tracks_user_playlist_path(@user, @playlist.permalink), 
    data: { target:'playlist-edit.sortUrl' }, class: 'hidden sort_url' %>
</div>

app/views/playlists/new.html.erb
<%= render(partial: 'users/user') unless white_theme_enabled? %>

<div class="playlists-new">

	<h1>Create a playlist</h1>
	<h2 class="spacey">Your playlist will become public as soon as it has some tracks in it</h2>

	<%= error_messages_for :playlist %>

	<div class="container static_content">
	<%= form_for [@user, @playlist] do |f| %>
	  <%= render partial: 'form', locals: {f: f} %>
	  <p>
	    <%= f.submit "Create" %>
	  </p>
	<% end %>
	</div>
</div>

app/views/playlists/show_white.html.erb
<%= content_for :head do %>
  <% unless @playlist.has_no_cover? %>
  <link rel="preload" href="<%= @playlist.cover(:greenfield) %>" as="image">
  <% end %>
<% end %>

<div id="playlist-and-track-content">
  <%= render 'playlist_white' %>

  <% if @asset %>
    <%= render partial: 'shared/asset_white' %>
  <% else %>
    <%= content_for(:body_class, 'cover-view') %>
    <div class="track-content track-content-cover-view">
      <div class="large-cover-and-credits">
        <div class="large-cover">
          <%= playlist_cover(@playlist, :greenfield) %>
        </div>
        <% if @playlist.has_any_links? %>
        <div class="playlist-options">
          <%= render partial: 'links' %>
        </div>
        <% end %>
      </div>
      <% if defined?(@old_cover_alert) and authorized?  %>
        <div class="playlist-cover-alert">
          Hey, <%= current_user.display_name %> this cover is from <strong><%= @playlist.pic.created_at.year %></strong> and is very blurry since we only saved a
          small 200x200px version of it.
          Go <%= link_to 'Upload a higher res one', edit_user_playlist_path(@playlist.user, @playlist),
            class: 'edit_playlist', :title => 'edit this playlist' %> if you can!</a>
        </div>
      <% end %>
      <% if @playlist.credits.present? %>
        <div class="playlist-credits">
        <%= markdown(@playlist.credits) %>
      </div>
      <% end %>
    </div>
  <% end %>
</div>